# Generated by Django 6.0.3 on 2026-04-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryorder',
            name='cloth_type',
            field=models.CharField(choices=[('Top Wear', 'Top Wear'), ('Bottom Wear', 'Bottom Wear'), ('Bedsheets', 'Bedsheets'), ('Curtains', 'Curtains'), ('Heavy Clothes', 'Heavy Clothes'), ('Mixed Clothes', 'Mixed Clothes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='laundryorder',
            name='laundry_type',
            field=models.CharField(choices=[('Washing', 'Washing'), ('Ironing', 'Ironing'), ('Dry Cleaning', 'Dry Cleaning'), ('Wash & Iron', 'Wash & Iron')], max_length=50),
        ),
    ]
