# Generated by Django 6.0.3 on 2026-04-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_alter_ordertracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Received'), (2, 'Out For Pickup'), (3, 'Washing'), (4, 'Out For Delivery'), (5, 'Delivered')], default=0),
        ),
    ]
