# Generated by Django 6.0.3 on 2026-04-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
