# Generated by Django 6.0.3 on 2026-04-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
