# Generated by Django 6.0.3 on 2026-04-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_bill_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='order_id',
        ),
    ]
