# Generated by Django 6.0.3 on 2026-04-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_remove_bill_order_id'),
        ('laundry', '0002_alter_laundryorder_cloth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laundry.laundryorder'),
        ),
    ]
