# Generated by Django 6.0.3 on 2026-04-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_bill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
